### PR TITLE
fix undocumented init function

### PR DESCRIPTION
**Pull request by geoffreyp**

### CODE REVIEW

**Comment by sjvrijn** [comment]
I've compared the output of this PR versus the current documentation, but I can't find any differences. Furthermore, the issue described in #33 is still present, see below for clarification:

aggregation_abc_init

**Comment by geoffreyp** [comment]
Did you clean the cache? Can you try after deleting the docs/doctrees, docs/html/ and docs/moead_framework/ folders ?

**Comment by sjvrijn** [comment]
Ah my bad, seems like `make clean` doesn't want to play nice with me on Windows.
The issue is now fixed for aggregation, but not for `offspring_generator.OffspringGeneratorGeneric`

**Comment by geoffreyp** [comment]
It is now fixed by the last commit f4fc38a

**Review by sjvrijn — APPROVED** [review]

**Pull request merged**
