### PR TITLE
issue 19 : A note on reproducibility

### PR DESCRIPTION
**Pull request by geoffreyp**
add the function set_seed()

### CODE REVIEW

**Comment by sjvrijn** [comment]
Looks good to me, do you agree @chkoar?

**Comment by sjvrijn** [comment]
You may want to include the use of your new `set_seed()` function in the tests:

 - [test_combinatorial_algorithm.py#L16](https://github.com/moead-framework/framework/blob/master/moead_framework/test/test_combinatorial_algorithm.py#L16)
 - [test_genetic_operator.py#L16](https://github.com/moead-framework/framework/blob/master/moead_framework/test/test_genetic_operator.py#L16)
 - [test_numerical_algorithm.py#L16](https://github.com/moead-framework/framework/blob/master/moead_framework/test/test_numerical_algorithm.py#L16)
 - [test_parent_selector.py#L19](https://github.com/moead-framework/framework/blob/master/moead_framework/test/test_parent_selector.py#L19)
 - [test_solution.py#L16](https://github.com/moead-framework/framework/blob/master/moead_framework/test/test_solution.py#L16)
 - [test_tool.py#L15](https://github.com/moead-framework/framework/blob/master/moead_framework/test/test_tool.py#L15)

**Comment by chkoar** [comment]
> Looks good to me, do you agree @chkoar?

Yes. But I have the impression that this approach is not safe in threaded environments.
A small naive example:

```python
import random
import numpy as np
import time
from moead_framework.problem.numerical import Zdt1
from concurrent.futures import ThreadPoolExecutor

random.seed(0)
problem = Zdt1(2)
expected = [
    [0.8444218515250481, 0.7579544029403025],
    [0.420571580830845, 0.25891675029296335],
]

solutions = []
solutions.append(problem.generate_random_solution().solution)
solutions.append(problem.generate_random_solution().solution)

assert np.array_equal(solutions, expected)

def worker(*args):
    time.sleep(np.random.randint(1,3))
    return problem.generate_random_solution().solution


for i in range(10):
    random.seed(0)
    with ThreadPoolExecutor() as executor:
        solutions = executor.map(worker, range(2))
        solutions = [x for x in solutions]

    assert np.array_equal(solutions, expected)

```

**Comment by geoffreyp** [comment]
From the [python documentation](https://docs.python.org/3/library/random.html#notes-on-reproducibility) : 

>  By re-using a seed value, the same sequence should be reproducible from run to run as long as multiple threads are not running.

The solution available is to instantiate a new instance of Random for each Thread and use this instance in problems and algorithms but it requires a lot of refactoring in the framework to replace each call of "import random" (and it is only for the Random module, the problem is maybe the same for np.random)

```
local_random = random.Random(n)
for i in xrange(100):
    a.append(local_random.randint(0, 1000))
```

I propose to add a note to prevent that this approach is not safe in threaded environments in python.

**Comment by sjvrijn** [comment]
A note in the docstring `set_seed` and wherever else relevant in the rest of the documentation would sufficiently address this issue for me.

**Review by sjvrijn — APPROVED** [review]
This would be sufficient for me

**Comment by chkoar** [comment]
Well, having [this](https://github.com/moead-framework/framework/commit/2b313c197ec40984bee253b6c5f791615a8e1060#diff-c8b67180d3f6c4160c8fbf40fdd5c2cde49827f6fa0a917c0e2e7c78ed3d993bR113) I believe is sufficient.

**Pull request merged**
